name: agora_rtm
description: Flutter wrapper around the Agora Real Time Message SDKs for Android and iOS.
version: 1.1.0
homepage: 'https://www.agora.io'
repository: 'https://github.com/AgoraIO/Flutter-RTM'
environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: '>=1.12.13+hotfix.6'
dependencies:
  flutter:
    sdk: flutter
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  plugin:
    platforms:
      android:
        package: io.agora.agorartm
        pluginClass: AgoraRtmPlugin
      ios:
        pluginClass: AgoraRtmPlugin

